"""initial schema

Revision ID: 98fca24d860a
Revises: 
Create Date: 2026-03-10 00:08:01.675317

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '98fca24d860a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('algorithm',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('slug', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('category', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('subcategory', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('author', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('paper_reference', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('complexity', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('best_use_case', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('compatibility_tabular', sa.Boolean(), nullable=False),
    sa.Column('compatibility_image', sa.Boolean(), nullable=False),
    sa.Column('compatibility_text', sa.Boolean(), nullable=False),
    sa.Column('compatibility_graph', sa.Boolean(), nullable=False),
    sa.Column('compatibility_timeseries', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_algorithm_category'), 'algorithm', ['category'], unique=False)
    op.create_index(op.f('ix_algorithm_name'), 'algorithm', ['name'], unique=False)
    op.create_index(op.f('ix_algorithm_slug'), 'algorithm', ['slug'], unique=True)
    op.create_index(op.f('ix_algorithm_subcategory'), 'algorithm', ['subcategory'], unique=False)
    op.create_table('algorithm_notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('algorithm_id', sa.Integer(), nullable=False),
    sa.Column('note_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['algorithm_id'], ['algorithm.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_algorithm_notes_algorithm_id'), 'algorithm_notes', ['algorithm_id'], unique=False)
    op.create_table('algorithm_parameters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('algorithm_id', sa.Integer(), nullable=False),
    sa.Column('parameter_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('default_value', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('parameter_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['algorithm_id'], ['algorithm.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_algorithm_parameters_algorithm_id'), 'algorithm_parameters', ['algorithm_id'], unique=False)
    op.create_table('implementation_status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('algorithm_id', sa.Integer(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('implemented_from_scratch', sa.Boolean(), nullable=False),
    sa.Column('implemented_library', sa.Boolean(), nullable=False),
    sa.Column('lab_created', sa.Boolean(), nullable=False),
    sa.Column('documentation_complete', sa.Boolean(), nullable=False),
    sa.Column('notes_added', sa.Boolean(), nullable=False),
    sa.Column('last_updated', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['algorithm_id'], ['algorithm.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_implementation_status_algorithm_id'), 'implementation_status', ['algorithm_id'], unique=True)
    op.create_table('lab',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('algorithm_id', sa.Integer(), nullable=False),
    sa.Column('lab_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('lab_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('framework', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['algorithm_id'], ['algorithm.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lab_algorithm_id'), 'lab', ['algorithm_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_lab_algorithm_id'), table_name='lab')
    op.drop_table('lab')
    op.drop_index(op.f('ix_implementation_status_algorithm_id'), table_name='implementation_status')
    op.drop_table('implementation_status')
    op.drop_index(op.f('ix_algorithm_parameters_algorithm_id'), table_name='algorithm_parameters')
    op.drop_table('algorithm_parameters')
    op.drop_index(op.f('ix_algorithm_notes_algorithm_id'), table_name='algorithm_notes')
    op.drop_table('algorithm_notes')
    op.drop_index(op.f('ix_algorithm_subcategory'), table_name='algorithm')
    op.drop_index(op.f('ix_algorithm_slug'), table_name='algorithm')
    op.drop_index(op.f('ix_algorithm_name'), table_name='algorithm')
    op.drop_index(op.f('ix_algorithm_category'), table_name='algorithm')
    op.drop_table('algorithm')
    # ### end Alembic commands ###
